language: python
python:
  - "3.8"
dist: bionic
group: beta

services:
  - docker

before_install:
  - export VERSION=github-travis-$TRAVIS_BUILD_NUMBER-$(date +%Y%m%d-%H%M%S)
  - echo "Build Version=$VERSION"
install:
  - make setup

script:
  - make travis-test

deploy:
  - provider: script
    script: make travis-deploy
    skip_cleanup: true
    on:
      branch: main

cache:
  directories:
    - $HOME/.cache/trivy
    - $HOME/.cache/pre-commit
